#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "100px"
# logo text will only show when logo is missing.
logo_text = "IllustratedBytes"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own

# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true
# copyright
copyright = "© 2021 Illustrated Bytes -  Made by <a href='https://gethugothemes.com/' target='_blank'>GetHugoThemes</a>"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""

# Navigation button
[navigation_button]
enable = false
label = "get a quote"
link = "contact"

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "https://example.innocraft.cloud/" # your matomo url
id = 1 # your matomo id

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"